include: package:lint/analysis_options.yaml

linter:
  rules:
    - prefer_single_quotes
    - omit_local_variable_types
    - avoid_relative_lib_imports
    - await_only_futures
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables

analyzer:
  strong-mode:
    implicit-casts: false

  errors:
    non_constant_identifier_names: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_redundant_argument_values: ignore
    prefer_const_declarations: error
    constant_identifier_names: ignore
    missing_required_param: error
    parameter_assignments: error
    unused_import: error
    sort_constructors_first: warning
    unused_field: warning
    unused_element: ignore
    overridden_fields: ignore
    unawaited_futures: warning
    unnecessary_final: error
    prefer_single_quotes: error
    omit_local_variable_types: error
    always_put_required_named_parameters_first: error
    avoid_relative_lib_imports: error
    await_only_futures: error
    prefer_typing_uninitialized_variables: error

  exclude:
    - "vendors/**"
    - "resources/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "lib/common/router/router.gr.dart"
    - "component_templates"
